Ecoin\BackendBundle\Entity\Ciudad:
    type: entity
    table: ciudad
    repositoryClass: Ecoin\BackendBundle\Entity\CiudadRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        nombre:
            type: string
            length: 255
        fchCreate:
            type: date
            column: fch_create

    manyToOne:
        pais:
            targetEntity: Pais
            inversedBy: ciudades
            joinColumn:
                name: pais_id
                referencedColumnName: id    

    lifecycleCallbacks: {  }
