Ecoin\BackendBundle\Entity\Interior:
    type: entity
    table: interior
    repositoryClass: Ecoin\BackendBundle\Entity\InteriorRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        descripcion:
            type: string
            length: '20'
    lifecycleCallbacks: {  }
