<?php

namespace Ecoin\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComerciohorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComerciohorRepository extends EntityRepository
{
}
