<?php

namespace Ecoin\FrontendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalRepository extends EntityRepository
{
	public function findByCategoria($pais_id, $categoria_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT local
            FROM FrontendBundle:Local local
            LEFT JOIN local.comercio comercio
            LEFT JOIN comercio.categoria categoria
            LEFT JOIN comercio.pais pais
            WHERE pais.id = :pais_id AND categoria.id = :categoria_id
        ")->setParameter('categoria_id', $categoria_id)
        ->setParameter('pais_id', $pais_id);

        return $query->getResult();
    }
}
