<?php

namespace Ecoin\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistritoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistritoRepository extends EntityRepository
{
	public function findByCiudadId($ciudad_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT distrito
            FROM BackendBundle:Distrito distrito
            LEFT JOIN distrito.ciudad ciudad
            WHERE ciudad.id = :ciudad_id
        ")->setParameter('ciudad_id', $ciudad_id);

        return $query->getResult();
    }
}
