<?php

namespace Ecoin\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetodoRepository extends EntityRepository
{
}
