<?php

namespace Ecoin\BackendBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonedaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonedaRepository extends EntityRepository
{
}
